./app/etc/* /usr/share/make-music/app/etc/
./app/scripts/* /usr/share/make-music/app/scripts/
./app/gui/images/* /usr/share/make-music/app/gui/images/
./make-music /usr/share/make-music/app/gui/

./LICENSE /usr/share/make-music/
./bin/make-music /usr/bin
./songs/* /usr/share/make-music/songs

./kdesktop/SonicPi.lnk /usr/share/kano-desktop/kdesk/kdesktop/
./icon/sonicpi.png /usr/share/kano-desktop/icons/
./icon/SonicPi-hover.png /usr/share/kano-desktop/icons/
