#!/bin/bash

set -e

WORKSPACE_DIR=/home/pi/.make-music
CONTENT_DIR=/home/pi/Music-content

echo "Removing workspaces"
rm -rv $WORKSPACE_DIR

echo "Removing content directory"
rm -rv $CONTENT_DIR

echo "Removing shortcuts"
rm -v /usr/bin/make-music

