#!/bin/bash

set -e

WORKSPACE_DIR=/home/pi/.make-music

echo "Removing workspaces"
rm -rv $WORKSPACE_DIR

echo "Removing content directory"
rm -rv $HOME/Music-content

echo "Removing shortcuts"
rm -v /usr/bin/make-music

